# Cloud Build configuration for Quantitativo Analyzer
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.cloud', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/quantitativo-analyzer-repo/quantitativo-analyzer:$COMMIT_SHA', '.']
  
  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/quantitativo-analyzer-repo/quantitativo-analyzer:$COMMIT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'quantitativo-analyzer'
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/quantitativo-analyzer-repo/quantitativo-analyzer:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--timeout'
    - '120s'
    - '--concurrency'
    - '10'
    - '--max-instances'
    - '10'
    - '--min-instances'
    - '0'
    - '--set-env-vars'
    - 'PORT=8080'

# Configure the image
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/quantitativo-analyzer-repo/quantitativo-analyzer:$COMMIT_SHA'

# Cloud Run service configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'quantitativo-analyzer'
